// <auto-generated />
using System;
using CategoryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CategoryService.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    partial class CategoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryService.Models.CategoryEntity", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Color = "#ef4444",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍔",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Food",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 2,
                            Color = "#3b82f6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🚗",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Transport",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 3,
                            Color = "#a855f7",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🎬",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Entertainment",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 4,
                            Color = "#10b981",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💊",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Health",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 5,
                            Color = "#f59e0b",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🛍",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Shopping",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 6,
                            Color = "#6366f1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💡",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Bills",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 7,
                            Color = "#14b8a6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "📚",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Education",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            CategoryId = 8,
                            Color = "#22c55e",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💰",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Salary",
                            Type = "INCOME"
                        },
                        new
                        {
                            CategoryId = 9,
                            Color = "#06b6d4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💻",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Freelance",
                            Type = "INCOME"
                        },
                        new
                        {
                            CategoryId = 10,
                            Color = "#84cc16",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "📈",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Investment",
                            Type = "INCOME"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
